
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface A5_104566776_Symbol {
  /* terminals */
  public static final int DIVIDE = 13;
  public static final int LBRA = 19;
  public static final int COMMENTS = 28;
  public static final int CASE = 34;
  public static final int HASH = 25;
  public static final int GREATER = 22;
  public static final int SEMI = 15;
  public static final int INT = 4;
  public static final int METHODERR = 32;
  public static final int LESS = 23;
  public static final int FOR = 9;
  public static final int MINUS = 14;
  public static final int RPAR = 18;
  public static final int COMMA = 16;
  public static final int WHILECOND = 38;
  public static final int PLUS = 11;
  public static final int MAIN = 6;
  public static final int IF = 7;
  public static final int INLINECOMMENTS = 29;
  public static final int ID = 26;
  public static final int EOF = 0;
  public static final int RETURN = 5;
  public static final int METHOD = 30;
  public static final int EQUAL = 21;
  public static final int error = 1;
  public static final int RBRA = 20;
  public static final int NUMBER = 2;
  public static final int BREAK = 37;
  public static final int VOID = 3;
  public static final int PRINTF = 24;
  public static final int SWITCH = 33;
  public static final int TIMES = 12;
  public static final int COLON = 35;
  public static final int ELSE = 8;
  public static final int WHILE = 10;
  public static final int DEFAULT = 36;
  public static final int LPAR = 17;
  public static final int QUOTES = 27;
  public static final int DO = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "VOID",
  "INT",
  "RETURN",
  "MAIN",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "PLUS",
  "TIMES",
  "DIVIDE",
  "MINUS",
  "SEMI",
  "COMMA",
  "LPAR",
  "RPAR",
  "LBRA",
  "RBRA",
  "EQUAL",
  "GREATER",
  "LESS",
  "PRINTF",
  "HASH",
  "ID",
  "QUOTES",
  "COMMENTS",
  "INLINECOMMENTS",
  "METHOD",
  "DO",
  "METHODERR",
  "SWITCH",
  "CASE",
  "COLON",
  "DEFAULT",
  "BREAK",
  "WHILECOND"
  };
}

