
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface A4Symbol {
  /* terminals */
  public static final int TIMES = 10;
  public static final int INLINECOMMENTS = 27;
  public static final int PLUS = 9;
  public static final int INT = 4;
  public static final int EQUAL = 19;
  public static final int QUOTES = 25;
  public static final int SEMI = 13;
  public static final int RBRA = 18;
  public static final int RETURN = 5;
  public static final int GREATER = 20;
  public static final int LBRA = 17;
  public static final int IF = 7;
  public static final int PRINTF = 22;
  public static final int COMMENTS = 26;
  public static final int ID = 24;
  public static final int HASH = 23;
  public static final int METHODERR = 29;
  public static final int COMMA = 14;
  public static final int EOF = 0;
  public static final int NUMBER = 2;
  public static final int DIVIDE = 11;
  public static final int MAIN = 6;
  public static final int METHOD = 28;
  public static final int MINUS = 12;
  public static final int error = 1;
  public static final int RPAR = 16;
  public static final int FOR = 8;
  public static final int VOID = 3;
  public static final int LPAR = 15;
  public static final int LESS = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "VOID",
  "INT",
  "RETURN",
  "MAIN",
  "IF",
  "FOR",
  "PLUS",
  "TIMES",
  "DIVIDE",
  "MINUS",
  "SEMI",
  "COMMA",
  "LPAR",
  "RPAR",
  "LBRA",
  "RBRA",
  "EQUAL",
  "GREATER",
  "LESS",
  "PRINTF",
  "HASH",
  "ID",
  "QUOTES",
  "COMMENTS",
  "INLINECOMMENTS",
  "METHOD",
  "METHODERR"
  };
}

